
name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Hugging Face CLI
      run: pip install huggingface_hub

    - name: Configure Git
      run: |
        git config --global user.email "olagunjujeremiah@gmail.com"
        git config --global user.name "Abayomi Olagunju"

    - name: Login to Hugging Face CLI
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo $HF_TOKEN | huggingface-cli login

    - name: Push to Hugging Face Spaces
      run: |
        git push space main --force https://$HF_TOKEN:@huggingface.co/spaces/jerryola1/help_research.git HEAD:main
