# name: Deploy to Hugging Face Spaces

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#       name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       name: Add Hugging Face as a remote
#       run: |
#         git remote add huggingface https://huggingface.co/spaces/jerryola1/Researcher_Helper
#         git fetch --unshallow || true
      
#       name: Push changes to Hugging Face
#       run: |
#         git push huggingface HEAD:main --force

#     - name: Install Hugging Face CLI
#       run: pip install huggingface_hub
      
#     - name: Log in to Hugging Face
#       run: huggingface-cli login ${{ secrets.HF_TOKEN }}


#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.8'  

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     # Add any other necessary build steps here

#     - name: Push to Hugging Face Spaces
#       env:
#         HF_USERNAME: ${{ secrets.HF_USERNAME }}
#         HF_TOKEN: ${{ secrets.HF_TOKEN }}
#       run: |
#         git config --global user.email "olagunjujeremiah@gmail.com"
#         git config --global user.name "Abayomi Olagunju"
#         git remote add huggingface  https://huggingface.co/spaces/jerryola1/Researcher_Helper
#         git fetch --unshallow || true
#         git push huggingface HEAD:main --force

name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Hugging Face CLI
      run: pip install huggingface_hub

    - name: Log in to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: huggingface-cli login ${{ secrets.HF_TOKEN }}

    - name: Configure git settings
      run: |
        git config --global user.email "olagunjujeremiah@gmail.com"
        git config --global user.name "Abayomi Olagunju"

    - name: Push changes to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Check if remote exists, to avoid errors
        if ! git remote get-url huggingface; then
          git remote add huggingface https://huggingface.co/spaces/jerryola1/Researcher_Helper.git
        fi
        # Ensure the repo is not shallow to allow complete history push
        git fetch --unshallow || true
        # This command pushes the code to Hugging Face Spaces
        git push huggingface HEAD:main --force
